nameOverride: ""
fullnameOverride: ""
global:
  namespaceOverride: ""
awsRegion: ""
clusterName: ""
serviceAccount:
  create: true
  annotations: {}
  name: ""
fluentbit:
  enabled: true
  namespaceOverride: ""
  name: fluent-bit
  configName: fluent-bit-config
  namespace: amazon-cloudwatch
  image:
    repository: amazon/aws-for-fluent-bit
    tag: 2.20.0
    pullPolicy: Always
  input:
    tag: "application.*"
    logPath: "/var/log/containers/*.log"
    fluentBitPath: "/var/log/containers/fluent-bit*"
    cloudwatchAgentPath: "/var/log/containers/cloudwatch-agent*"
    excludePath: "/var/log/containers/cloudwatch-agent*, /var/log/containers/fluent-bit*, /var/log/containers/aws-node*, /var/log/containers/kube-proxy*"
    dockerMode: "On"
    dockerModeFlush: 5
    docerModeParser: "container_firstline"
    parser: "docker"
    db: "/var/fluent-bit/state/flb_container.db"
    memBufLimit: "50MB"
    fluentBitMemBufLimit: "5MB"
    skipLongLines: "On"
    refreshInterval: 10
    rotateWait: 30
    storageType: "filesystem"
    readFromHead: "On"
    readFromTail: "Off"
  env:
    httpServer: On
    httpPort: "2020"
    readFromHead: "Off"
    readFromTail: "On"

adot:
  enabled: true
  namespaceOverride: ""
  name: aws-otel-collector
  image:
    repository: amazon/aws-otel-collector
    tag: v0.13.0
    pullPolicy: IfNotPresent
  namespace: aws-otel-eks

adotCollector:
  daemonSet:
    enabled: true
    nameOverride: ""
    fullnameOverride: ""
    daemonSetName: adot-collector-daemonset
    namespace: aws-cloudwatch-metrics
    namespaceOverride: ""
    serviceAccount:
      create: true
      name: adot-collector-sa
    clusterRoleName: adot-collector-role
    clusterRoleBindingName: adot-collector-role-binding
    configMap:
      name: adot-conf
      lables:
      app: opentelemetry
      component: adot-conf
    containersName: adot-collector-container
    image:
      repository: amazon/aws-otel-collector
      tag: v0.13.0
      pullPolicy: IfNotPresent
    env:
      - name: K8S_NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: HOST_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
      - name: HOST_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: K8S_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
    command:
      - "/awscollector"
      - "--config=/conf/adot-config.yaml"
    resources:
      limits:
        cpu: 200m
        memory: 200Mi
      requests:
        cpu: 200m
        memory: 200Mi
    volumes:
      - configMap:
          name: adot-conf
          items:
            - key: adot-config
              path: adot-config.yaml
        name: adot-config-vol
      - name: rootfs
        hostPath:
          path: /
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      - name: varlibdocker
        hostPath:
          path: /var/lib/docker
      - name: sys
        hostPath:
          path: /sys
      - name: devdisk
        hostPath:
          path: /dev/disk/
    volumeMounts:
      - name: rootfs
        mountPath: /rootfs
        readOnly: true
      - name: dockersock
        mountPath: /var/run/docker.sock
        readOnly: true
      - name: varlibdocker
        mountPath: /var/lib/docker
        readOnly: true
      - name: sys
        mountPath: /sys
        readOnly: true
      - name: devdisk
        mountPath: /dev/disk
        readOnly: true
      - name: adot-config-vol
        mountPath: /conf
    extensions:
    healthCheck:
    receivers:
      collectionInterval:
      containerOrchestrator:
      addServiceAsAttribute:
      preferFullPodName:
    processors:
      timeout: 60s
    exporters:
      namespace: ContainerInsights
      logGroupName:
      logStreamName: InputNodeName
      enabled: true
      dimensionRollupOption: NoDimensionRollup
      parseJsonEncodedAttrValues: [Sources, kubernetes]
    metricDeclarations: |
      # node metrics
      - dimensions: [[NodeName, InstanceId, ClusterName]]
        metric_name_selectors:
          - node_cpu_utilization
          - node_memory_utilization
          - node_network_total_bytes
          - node_cpu_reserved_capacity
          - node_memory_reserved_capacity
          - node_number_of_running_pods
          - node_number_of_running_containers
      - dimensions: [[ClusterName]]
        metric_name_selectors:
          - node_cpu_utilization
          - node_memory_utilization
          - node_network_total_bytes
          - node_cpu_reserved_capacity
          - node_memory_reserved_capacity
          - node_number_of_running_pods
          - node_number_of_running_containers
          - node_cpu_usage_total
          - node_cpu_limit
          - node_memory_working_set
          - node_memory_limit

      # pod metrics
      - dimensions: [[PodName, Namespace, ClusterName], [Service, Namespace, ClusterName], [Namespace, ClusterName], [ClusterName]]
        metric_name_selectors:
          - pod_cpu_utilization
          - pod_memory_utilization
          - pod_network_rx_bytes
          - pod_network_tx_bytes
          - pod_cpu_utilization_over_pod_limit
          - pod_memory_utilization_over_pod_limit
      - dimensions: [[PodName, Namespace, ClusterName], [ClusterName]]
        metric_name_selectors:
          - pod_cpu_reserved_capacity
          - pod_memory_reserved_capacity
      - dimensions: [[PodName, Namespace, ClusterName]]
        metric_name_selectors:
          - pod_number_of_container_restarts

      # cluster metrics
      - dimensions: [[ClusterName]]
        metric_name_selectors:
          - cluster_node_count
          - cluster_failed_node_count

      # service metrics
      - dimensions: [[Service, Namespace, ClusterName], [ClusterName]]
        metric_name_selectors:
          - service_number_of_running_pods

      # node fs metrics
      - dimensions: [[NodeName, InstanceId, ClusterName], [ClusterName]]
        metric_name_selectors:
          - node_filesystem_utilization

      # namespace metrics
      - dimensions: [[Namespace, ClusterName], [ClusterName]]
        metric_name_selectors:
          - namespace_number_of_running_pods

    service:
      pipelines:
      metrics:
      receivers: [awscontainerinsightreceiver]
      processors: [batch/metrics]
      exporters: [awsemf]
      extensions: [health_check]

  sidecar:
    enabled: false
    name: adot-sidecar
    namespace: adot-sidecar-namespace
    namespaceOverride: ""
    regionS3: "us-west-2"
    replicas: 1
    containers:
      name: adot-emitter
      image: "aottestbed/aws-otel-collector-sample-app:java-0.1.0"
      pullPolicy: Always
    otelOtlpEndPointValue: "localhost:4317"
    otelResourceAttributesValue: "service.namespace=AWSObservability,service.name=CloudWatchEKSService"
    image:
      name: aws-otel-collector
      repository: amazon/aws-otel-collector
      tag: latest
      pullPolicy: Always
    resources:
      limits:
        cpu: 256m
        memory: 512Mi
      requests:
        cpu: 32m
        memory: 24Mi
