{{- if .Values.adotMetrics.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.adotMetrics.configMap.name }}
  namespace: {{ .Values.adotMetrics.namespace }}
  labels:
    app: {{ .Values.adotMetrics.configMap.app }}
    component: {{ .Values.adotMetrics.configMap.component }}
data:
  adot-config: |
    extensions:
      health_check:

    receivers:
      awscontainerinsightreceiver:
        # all parameters are optional
        collection_interval: {{ .Values.adotMetrics.config.receivers.collection_interval }}
        container_orchestrator: {{ .Values.adotMetrics.config.receivers.container_orchestrator }}
        add_service_as_attribute: {{ .Values.adotMetrics.config.receivers.add_service_as_attribute }}
        prefer_full_pod_name: {{ .Values.adotMetrics.config.receivers.prefer_full_pod_name }}

    processors:
      batch/metrics:
        timeout: {{ .Values.adotMetrics.config.processors.timeout }}

    exporters:
      awsemf:
        namespace: {{ .Values.adotMetrics.config.exporters.awsemf.namespace }}
        log_group_name: '/aws/containerinsights/{{ .Values.adotMetrics.clusterName }}/performance'
        log_stream_name: {{ .Values.adotMetrics.config.exporters.awsemf.log_stream_name }}
        resource_to_telemetry_conversion:
          enabled: {{ .Values.adotMetrics.config.exporters.awsemf.resource_to_telemetry_conversion.enabled }}
        dimension_rollup_option: {{ .Values.adotMetrics.config.exporters.awsemf.dimension_rollup_option }}
        parse_json_encoded_attr_values: {{ .Values.adotMetrics.config.exporters.awsemf.parse_json_encoded_attr_values }}
        metric_declarations:
          {{ .Values.adotMetrics.config.metric_declarations | nindent 10 }}

    service:
      pipelines:
        metrics:
          receivers: {{ .Values.adotMetrics.config.service.receivers }}
          processors: {{ .Values.adotMetrics.config.service.processors }}
          exporters: {{ .Values.adotMetrics.config.service.exporters }}

      extensions: {{ .Values.adotMetrics.config.service.extensions }}

{{- end -}}