{{- if .Values.adotMetrics.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.adotMetrics.daemonSet.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      name: {{ .Values.adotMetrics.daemonSet.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.adotMetrics.daemonSet.name }}
    spec:
      containers:
        - name: {{ .Values.adotMetrics.daemonSet.containers.name }}
          image: "{{ .Values.adotMetrics.daemonSet.image.repository }}:{{ .Values.adotMetrics.daemonSet.image.tag }}"
          imagePullPolicy: {{ .Values.adotMetrics.daemonSet.image.pullPolicy }}
          env:
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - "/awscollector"
            - "--config=/conf/otel-agent-config.yaml"
          volumeMounts:
            - name: rootfs
              mountPath: /rootfs
              readOnly: true
            - name: dockersock
              mountPath: /var/run/docker.sock
              readOnly: true
            - name: varlibdocker
              mountPath: /var/lib/docker
              readOnly: true
            - name: sys
              mountPath: /sys
              readOnly: true
            - name: devdisk
              mountPath: /dev/disk
              readOnly: true
            - name: otel-agent-config-vol
              mountPath: /conf
          resources:
            {{- toYaml .Values.adotMetrics.daemonSet.resources | nindent 12 }}
      volumes:
        - configMap:
            name: {{ .Values.adotMetrics.configMap.name }}
            items:
              - key: {{ .Values.adotMetrics.daemonSet.volumes.key }}
                path: {{ .Values.adotMetrics.daemonSet.volumes.path }}
          name: {{ .Values.adotMetrics.daemonSet.volumes.name }}
        - name: rootfs
          hostPath:
            path: /
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
        - name: varlibdocker
          hostPath:
            path: /var/lib/docker
        - name: sys
          hostPath:
            path: /sys
        - name: devdisk
          hostPath:
            path: /dev/disk/
      serviceAccountName: {{ .Values.adotMetrics.serviceAccount.name  }}
{{- end -}}