apiVersion: v1
kind: Service
metadata:
  name: {{ include "adot-helm-eks-ec2.fullname" . }}
  labels:
    {{- include "adot-helm-eks-ec2.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "adot-helm-eks-ec2.selectorLabels" . | nindent 4 }}
